default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: hi
  host: localhost
  port: 5432

development:
  <<: *default
  database: calculator_app_development

test:
  <<: *default
  database: calculator_app_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
