default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: calculator_app_development
  username: postgres
  password: hi
  host: localhost
  port: 5432

test:
  <<: *default
  database: calculator_app_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5

  cable:
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5

